### PR TITLE
languages/en-GB - Sync new language keys

### PR DESCRIPTION
**Pull request by CloudTheWolf**
Added new Language Keys.

### CODE REVIEW

**Review by InZidiuZ — CHANGES_REQUESTED** [review]
Syntax errors! You should run it through the locale parser before submitting PRs

**Comment by CloudTheWolf** [comment]
Added additional keys and fixed syntax errors, no errors in parser

**Review by InZidiuZ — CHANGES_REQUESTED** [review]
There are still some problems:
```
Unknown field-type: 'TableKey'
Trailing comma at line 4740
Missing locale: creation/turn_right
Missing locale: creation/turn_left
Missing locale: creation_menu/accessory
Missing locale: creation_menu/undershirt
Missing locale: creation_menu/kevlar
Missing locale: creation_menu/badge
Missing locale: creation_menu/torso_two
Missing locale: inventory/battle_royale_item_disallowed
Missing locale: spawn/battle_royale
Undeeded locale: creation/male
Undeeded locale: creation/female
Undeeded locale: creation/city_registration
Undeeded locale: creation/citizen_id
```

**Comment by CloudTheWolf** [comment]
Resynced with en-US all errors cleaned except `Unknown field-type: 'TableKey'` but this looks to be an issue even when comparing en-US with itself

**Comment by InZidiuZ** [comment]
Yes that is like that because "in" is a keyword in Lua & I have to wrap it in [""] to not have any errors, so you can safely ignore that

**Review by InZidiuZ — APPROVED** [review]

**Pull request merged**
