### PR TITLE
Update pl-PL.lua

### PR DESCRIPTION
**Pull request by JakubZlotek**
Beautified code

### CODE REVIEW

**Comment by InZidiuZ** [comment]
Does this imply that #8 should be closed in favor of this one?

**Comment by JakubZlotek** [comment]
yeah

**Review by InZidiuZ — CHANGES_REQUESTED** [review]
We use 4-wide tab indents. I request you change it as to not pollute the repository.

**Comment by JakubZlotek** [comment]
image
i don't get it...

**Comment by JakubZlotek** [comment]
image
exactly same as et-EE

**Comment by InZidiuZ** [comment]
Perhaps it's your editor? Both on GitHub online as well as on my editor et-EE is fine.

**Comment by JakubZlotek** [comment]
image

**Comment by InZidiuZ** [comment]
You'll have to figure that out yourself. Maybe try a different editor, as if you check the [raw file](https://raw.githubusercontent.com/InZidiuZ/op-framework-public/6c43550b2aa4f0078582e4508ebee6f330fbaf63/languages/pl-PL.lua), you can see that it's definitely using 2-width tabs, especially when compared to the [et-EE raw file](https://raw.githubusercontent.com/InZidiuZ/op-framework-public/master/languages/et-EE.lua).

**Review by InZidiuZ — CHANGES_REQUESTED** [review]
*Do not* put the entire file into a random online 'beautifier'. It'll lose its similarities to the other language files which will make it more difficult to maintain in the future as well as pollute the repository.

**Comment by JakubZlotek** [comment]
check it now
<3

**Review by InZidiuZ — APPROVED** [review]
Perfect 😄

**Pull request merged**
