### PR TITLE
Update et-EE.lua

### PR DESCRIPTION
**Pull request by glocknine234**

### CODE REVIEW

**Comment by InZidiuZ** [comment]
...did you even bother checking for errors?

**Comment by glocknine234** [comment]
I forgot to. It's fixed now.

**Comment by InZidiuZ** [comment]
I looked... and no, still has syntax errors

**Comment by glocknine234** [comment]
I don't understand. I fixed all those syntax errors ,but it seems that it doesn't save the changes or something however when I click on the file it looks fine. Line 157 keeps reverting fixes back, there should be comma "," ,but it dissapears everytime.

**Pull request closed without merging**
