### PR TITLE
Update et-EE.lua

### PR DESCRIPTION
**Pull request by glocknine234**

### CODE REVIEW

**Comment by InZidiuZ** [comment]
#13?

**Comment by glocknine234** [comment]
What #13?

**Comment by glocknine234** [comment]
Ooh i didnt edit that

**Comment by InZidiuZ** [comment]
Should I close #13 in favor of this one?

**Comment by glocknine234** [comment]
Yeah

**Comment by InZidiuZ** [comment]
There seems to still be syntax errors here

**Comment by glocknine234** [comment]
How? There's literally none.

**Comment by glocknine234** [comment]
Done, updated. Everything is fine.

**Review by InZidiuZ — APPROVED** [review]

**Pull request merged**
